### ISSUE TITLE
Resulting recommendations include duplicated tracks

### ISSUE THREAD

**Issue by mike-mo** [RyanRussell00/personal-dj#13]
Inputs:
* **Track name:** Stand Atlantic - Eviligo
* **Danceable**: 8
* **Hype**: 8
* **Popular**: 5
* **Songs**: 15

Observed: Tracks 1 and 7 are both Stand Atlantic - Skinny Dipping
Expected: No tracks repeat in playlist

Tracks appear to have different IDs, which may make this a little trickier to solve, but it would be a welcome improvement.

**Comment by astriskit** [comment]
If the track-id is different - then duplication is at spotify too; 
Did you confirm the issue @RyanRussell00  btw?

**Comment by RyanRussell00** [comment]
@astriskit I have not confirmed this issue.
Does the Spotify documentation say that if the track-id is different but the tracks are the same, it's a Spotify thing?

**Comment by astriskit** [comment]
@RyanRussell00 it seems like this/duplication is a thing; Found something over the internet that kinda deals with similar thing - https://developer.spotify.com/community/showcase/spotify-dedup/

reference - https://community.spotify.com/t5/Desktop-Linux/Any-way-to-identify-remove-duplicate-tracks-to-save-space/m-p/1570750

**Comment by RyanRussell00** [comment]
@astriskit Thanks for that. 
It seems as if it's a Spotify issue if the tracks are released twice, and there are apps such as Spotify Dedup that can remove duplicates. But I don't think this is a feature we will be implementing.
