### ISSUE TITLE
Found a new way to bypass login

### ISSUE THREAD

**Issue by chinmaykunkikar** [RyanRussell00/personal-dj#15]
I see that you've already worked on this issue [before](https://github.com/RyanRussell00/personal-dj/commit/68325384608bd76df79474a93a9813cedb4bfa6f). But I found a new way that will bypass the login screen.

Just by putting `#authorized=access_granted` after the app URL will bypass the login screen.

**Comment by RyanRussell00** [comment]
Thanks for bringing this to our attention

**Comment by RyanRussell00** [comment]
Issue resolved in latest version: 1.1
Please reopen this issue if you see that it's not resolved. Thanks!
