### ISSUE TITLE
Save playlist created a playlist based on another song

### ISSUE THREAD

**Issue by Parth-Vader** [RyanRussell00/personal-dj#2]
I got a playlist recommended on my song, but when I clicked to save it, I got a whole another playlist based on another song (which was very good no doubt).

Pretty sure this is unintended behavior.

Great app though.

**Comment by RyanRussell00** [comment]
@Parth-Vader Did you make sure to click on "Generate Recommendations" before saving the playlist?

**Comment by RyanRussell00** [comment]
This has become a confirmed bug. Moving all future comments regarding this issue to issue #6 
Thank you for reporting this.
