### ISSUE TITLE
Show number of recommended tracks

### ISSUE THREAD

**Issue by RyanRussell00** [RyanRussell00/personal-dj#22]
When the user generates a list of tracks we should show how many tracks were actually able to get generated. Maybe at the top of the recommendations list, we say "Found 24 tracks" or whatever.

**Comment by DreamsOfImran** [comment]
Hi, can I work on this?

**Comment by RyanRussell00** [comment]
@DreamsOfImran All yours! Please open a PR from your fork when complete. Thanks!!

**Comment by RyanRussell00** [comment]
@DreamsOfImran Looks like PR #26 was opened to resolve this. If you'd like you can help answer my comments on that PR instead. Sorry about that

**Comment by RyanRussell00** [comment]
Closed with PR #26
