### ISSUE TITLE
Toggle between explicit and non-explicit music

### ISSUE THREAD

**Issue by RyanRussell00** [RyanRussell00/personal-dj#23]
The response from the Spotify API contains data about whether certain tracks are explicit or not. The user should have a toggle switch that lets them toggle between Explicit and non-explicit.

Maybe the easiest way to do this is to generate 2 separate lists when recommendations are loaded in, 1 with all the tracks and 1 with only non-explicit tracks. Then when the user toggles we just show different tracks and send the selected list to Save as playlist.

Idea suggested by: RippedGeek from Reddit. Thanks Geek!

![image](https://user-images.githubusercontent.com/35180491/95007832-f3fd6480-05c8-11eb-9e35-48c64b83706a.png)

**Comment by megabyte98** [comment]
hey  @RyanRussell00  can I handle this issue?

**Comment by RyanRussell00** [comment]
@megabyte98 PR #25 has already been opened to resolve this. Please feel free to take up another issue, or add some more features to the app!

**Comment by megabyte98** [comment]
ok @RyanRussell00  but @ad-dan please comment before working on an issue and making a PR so that others are informed
