### ISSUE TITLE
Tracks with quotes in the title are not selected and some tracks not shown due to popularity

### ISSUE THREAD

**Issue by luiserdef** [RyanRussell00/personal-dj#27]
**1. Songs with quotes in the title are not selected**
When the track is selected, the selected animation is not shown, this happens with songs that have quotation marks in the title.

**To Reproduce**
Input:
Track name: Hawaiian Roller Coaster Ride - From "Lilo & Stitch"/Soundtrack
or
Track name: hawai (_This is the easiest way to see the problem_)

and select the track

**Expected behavior**
The song should be selected but nothing happens

**2. Some tracks not shown due to popularity**
In the section "How popular do you want the recommendations? (1 to 100)", when the users add for example 84 or more, no results are shown (recommended tracks list) because there are no songs that have that popularity value, so it will look like there is a mistake because nothing is shown. There may be a way to show the user a notification when there are no results to display.

**To Reproduce**
Input:
Track name: When you where young
How popular do you want the recommendations? (1 to 100): 84 or more

**Expected behavior**
Show a notification that there are no results to display

If you enter 83 or less, you can see the differences in the results

**If there is no problem I can work to solve these issues**

**Comment by RyanRussell00** [comment]
Thanks for finding this bug. If you'd like, you can assign yourself to this issue and work on it, otherwise just leave it open for someone else to take over. Thanks!

**Comment by luiserdef** [comment]
I will work on this
