### ISSUE TITLE
add a favicon to the head of the website

### ISSUE THREAD

**Issue by thesmartdeveloperr** [RyanRussell00/personal-dj#3]
It would be pretty nice to include a nice favicon along with the title for more familiarity, as now the webpage renders default favicon(that earth like one). @RyanRussell00 what do you think?

**Comment by RyanRussell00** [comment]
@thesmartdeveloperr Sounds good! If you have any good favicon ideas (copyright free pls) please link them!

**Comment by RyanRussell00** [comment]
If anyone takes this issue please provide a URL to the original favicon image just so I can check for copyright rules

**Comment by nidhishs** [comment]
Hey. I can design a custom favicon for you guys if you want. I have some experience with graphic designing.

**Comment by RyanRussell00** [comment]
@nidhishs Sounds good! Thank you!

**Comment by nidhishs** [comment]
@RyanRussell00 I just designed this real quick as a v1.0

I used the colours I found on your website. Let me know of any issues or any changes you want. 
![PdJ](https://user-images.githubusercontent.com/55269918/94997862-3e251c80-05ae-11eb-8f3a-c92fa9f64ac4.png)

Also, if you don't mind, could you please add the Hacktoberfest label to this issue so it contributes towards my PRs?

**Comment by RyanRussell00** [comment]
@nidhishs I really like it! My only suggestion is to remove the white cable thingy, I think it looks cleaner without it.
Let me know what you think, and if it's ready to go please submit a PR.
I also added the Hacktoberfest label.

**Comment by nidhishs** [comment]
> @nidhishs I really like it! My only suggestion is to remove the white cable thingy, I think it looks cleaner without it.
> Let me know what you think, and if it's ready to go please submit a PR.
> I also added the Hacktoberfest label.

Sure. The white pointer does seem a bit out of place. I'll add a PR. Please let me know in which format and where I should add the file.

Update: @RyanRussell00 I have added a PR to address this issue. Check it out.
