### ISSUE TITLE
Make all inputs optional

### ISSUE THREAD

**Issue by RyanRussell00** [RyanRussell00/personal-dj#37]
Convert all the inputs (except for seeded track) to optional, allowing people to leave fields such as "popularity", "danceability", etc. blank if they wish to.
The seeded track is a mandatory field. 
Follow API documentation for Recommendations API to see what's allowed to be optional.
https://developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/

**Comment by maw1a** [comment]
I would like to work on this.

**Comment by RyanRussell00** [comment]
@maw1a All yours. Please open a PR and assign me as a reviewer when it's ready!

We already have some optional inputs on the app, you can just follow that same style for the rest of the inputs. Please look at the API documentation to see what inputs are allowed to be optional and which aren't.

Please note that if an optional input is filled out, but is invalid, the UI should still show an error beside the field, but it can still go ahead and generate the recommendations. You can see what I mean if you go to the site, search for a track, enter valid required inputs, open the optional inputs, and enter an invalid optional input. It will show you an error beside the form saying that the input is invalid, but it will still generate the playlist.

Let me know if you have any questions!

**Comment by RyanRussell00** [comment]
This issue is open for anyone to work on
