### ISSUE TITLE
Playlists not being added to users library

### ISSUE THREAD

**Issue by JakeCapra** [RyanRussell00/personal-dj#4]
Not sure if this is an issue with the Spotify API or the website itself, but when I save a playlist nothing happens.

**Comment by RyanRussell00** [comment]
This is most likely due to the user not inputting the correct values in the form. We need to add better form validation and error message handling. 
If issue #5 doesn't resolve this please reopen this issue. Thanks.

**Comment by RyanRussell00** [comment]
Version 1.1 should resolve most issues regarding this. Please reopen the issue is the problem persists.
