### ISSUE TITLE
Confirm before creating duplicate playlists

### ISSUE THREAD

**Issue by RyanRussell00** [RyanRussell00/personal-dj#7]
If the user has already created a playlist and they try creating a playlist based on the exact same parameters, we need to have a pop up that confirms that this is an intended action. Or else they could accidentally end up making a half-dozen playlists.

**Comment by utkarsh4321** [comment]
Hii @RyanRussell00 i want to contribute into this

**Comment by RyanRussell00** [comment]
> 
> 
> Hii @RyanRussell00 i want to contribute into this

@utkarsh4321 It's all yours! Just create a new fork and open a Pull Request when it's done.
You should read the [GETTING_STARTED](https://github.com/RyanRussell00/personal-dj/blob/master/GETTING-STARTED.md)

**Comment by utkarsh4321** [comment]
hii @RyanRussell00  can you tell me where I can see my playlist.

**Comment by RyanRussell00** [comment]
@utkarsh4321 if you mean where you can see the saved playlist, that will be in your Spotify account. But before you save the playlist it will load the recommendations and you can see it there. In the code, the recommendations are being saved as an array.

**Comment by RyanRussell00** [comment]
@utkarsh4321 Can you please update the button to say something like "playlist successfully saved" or give some sort of other confirmation that the playlist was saved. Then if the user clicks the button again prompt them for confirmation to save a duplicate.

Let me know if you have any questions, thanks!

**Comment by utkarsh4321** [comment]
I will talk into this don't worry about it

**Comment by utkarsh4321** [comment]
You mean that if there is a playlist in there Spotify account then you need to show the button text "playlist successfully saved" or if he clicks the button with same parameters then modal will prompt for confirmation.

**Comment by RyanRussell00** [comment]
@utkarsh4321 
I think that's a multi-part question:
- When the user saves a playlist for the first time there should be some sort of confirmation that it was successful. So the button text could change, a modal, a label, etc.
- If the user hits the "save" button again without generating new recommendations, there should be a modal saying "Playlist already saved, do you want to save a duplicate?".

For the second approach, you could use some sort of flag in the save playlist function that gets reset every time the user hits the "generate recommendations" button.

Let me know if that makes sense, thanks!

**Comment by utkarsh4321** [comment]
ok thanks i will try to complete asap

**Comment by utkarsh4321** [comment]
Hi @RyanRussell00 you want that when anybody hits save playlist button without changing any recommendation then we have to show the confirmation message.

**Comment by utkarsh4321** [comment]
Hii @RyanRussell00 There is any way so that I get the saved playlist and match it's already saved or not.

**Comment by RyanRussell00** [comment]
@utkarsh4321 
There is no easy way of getting the saved playlist. Instead, when they hit the "Save Playlist" button set a boolean flag to true, and if they try hitting "Save Playlist" again and the flag is true, prompt them for confirmation. Then when they hit "Get Recommendations" you can set the boolean flag to false. That's one approach that I thought of and it seems simple enough, but you're welcome to implement it however you'd like.

Thanks!

**Comment by utkarsh4321** [comment]
ok, no problem I will implement it according to your requirement.

**Comment by utkarsh4321** [comment]
Hii @RyanRussell00  can you please tell me if there is any problem with PR so I will try to fix it asap. And if there is no any problem then merge it. I try to fix as your requirement but if there is any problem tell me.

**Comment by RyanRussell00** [comment]
@utkarsh4321 
Hey, I haven't forgotten about this! I have been caught up lately and I'm hoping that I can sit down and handle the issues/PR for this project this weekend.
I will for sure get it handled before end of October to make sure you get the hacktoberfest credit!
Thanks!

**Comment by utkarsh4321** [comment]
Thanks 😊

**Comment by RyanRussell00** [comment]
Thank you for this contribution! It's fantastic!
